/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SnippetCommandsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
function getCustomCss(app) {
  const customCss = app.customCss;
  if (!customCss || !Array.isArray(customCss.snippets))
    return null;
  return customCss;
}
function toCommandId(snippetName) {
  return `toggle-snippet-${snippetName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "snippet"}`;
}
var SnippetPickerModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
    this.setPlaceholder("Type a snippet name to toggle\u2026");
  }
  getItems() {
    return this.plugin.getSnippetNames();
  }
  getItemText(item) {
    return `${this.plugin.isEnabled(item) ? "\u2713 " : "\u25CB "}${item}`;
  }
  onChooseItem(item) {
    void this.plugin.toggleSnippet(item);
  }
};
var SnippetCommandsPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    /** Command ids currently registered for individual snippets (id -> snippet name). */
    this.snippetCommandIds = /* @__PURE__ */ new Map();
  }
  async onload() {
    this.addCommand({
      id: "toggle-snippet-picker",
      name: "Toggle snippet\u2026",
      callback: () => {
        if (this.getSnippetNames().length === 0) {
          new import_obsidian.Notice("No CSS snippets found in .obsidian/snippets/");
          return;
        }
        new SnippetPickerModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "enable-all-snippets",
      name: "Enable all snippets",
      callback: () => void this.setAll(true)
    });
    this.addCommand({
      id: "disable-all-snippets",
      name: "Disable all snippets",
      callback: () => void this.setAll(false)
    });
    this.addCommand({
      id: "reload-snippet-commands",
      name: "Reload snippet list",
      callback: () => {
        this.refreshSnippetsFromDisk();
        this.registerSnippetCommands();
        new import_obsidian.Notice(`Reloaded ${this.getSnippetNames().length} snippet(s)`);
      }
    });
    this.app.workspace.onLayoutReady(() => {
      this.refreshSnippetsFromDisk();
      this.registerSnippetCommands();
    });
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file.path.includes("snippets/"))
          this.reregister();
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file.path.includes("snippets/"))
          this.reregister();
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file.path.includes("snippets/") || oldPath.includes("snippets/"))
          this.reregister();
      })
    );
    let lastSeen = "";
    this.registerInterval(
      window.setInterval(() => {
        const key = this.getSnippetNames().join("\n");
        if (key !== lastSeen) {
          lastSeen = key;
          if (key !== "")
            this.reregister();
        }
      }, 5e3)
    );
  }
  onunload() {
  }
  // ---------- public API used by the modal ----------
  getSnippetNames() {
    var _a, _b;
    return (_b = (_a = getCustomCss(this.app)) == null ? void 0 : _a.snippets.slice().sort()) != null ? _b : [];
  }
  isEnabled(snippetName) {
    var _a, _b;
    return (_b = (_a = getCustomCss(this.app)) == null ? void 0 : _a.enabledSnippets.has(snippetName)) != null ? _b : false;
  }
  async toggleSnippet(snippetName) {
    const customCss = getCustomCss(this.app);
    if (!customCss) {
      new import_obsidian.Notice("Snippet API not available yet, try again in a moment.");
      return;
    }
    const next = !customCss.enabledSnippets.has(snippetName);
    customCss.setCssEnabledStatus(snippetName, next);
    new import_obsidian.Notice(`Snippet \u201C${snippetName}\u201D ${next ? "enabled" : "disabled"}`);
  }
  async setAll(enabled) {
    const customCss = getCustomCss(this.app);
    if (!customCss) {
      new import_obsidian.Notice("Snippet API not available yet, try again in a moment.");
      return;
    }
    for (const name of customCss.snippets) {
      customCss.setCssEnabledStatus(name, enabled);
    }
    new import_obsidian.Notice(
      enabled ? `Enabled ${customCss.snippets.length} snippet(s)` : `Disabled ${customCss.snippets.length} snippet(s)`
    );
  }
  // ---------- internal ----------
  reregister() {
    this.refreshSnippetsFromDisk();
    this.registerSnippetCommands();
  }
  /** Ask Obsidian to rescan the snippets folder (best-effort). */
  refreshSnippetsFromDisk() {
    try {
      const customCss = getCustomCss(this.app);
      if (customCss && typeof customCss.readSnippets === "function") {
        customCss.readSnippets();
      } else if (customCss && typeof customCss.requestLoadSnippets === "function") {
        customCss.requestLoadSnippets();
      }
    } catch (e) {
    }
  }
  /**
   * Register one `Toggle snippet: <name>` command per detected snippet.
   * Stale commands are removed so deleted/renamed snippets don't linger.
   */
  registerSnippetCommands() {
    var _a;
    const names = this.getSnippetNames();
    const wanted = /* @__PURE__ */ new Map();
    for (const name of names) {
      const baseId = toCommandId(name);
      let id = baseId;
      let n = 2;
      while (wanted.has(id) && wanted.get(id) !== name) {
        id = `${baseId}-${n++}`;
      }
      wanted.set(id, name);
      if (this.snippetCommandIds.get(id) === name)
        continue;
      this.addCommand({
        id,
        name: `Toggle snippet: ${name}`,
        callback: () => void this.toggleSnippet(name)
      });
      this.snippetCommandIds.set(id, name);
    }
    for (const [id, name] of [...this.snippetCommandIds]) {
      if (wanted.get(id) !== name) {
        (_a = this.removeCommand) == null ? void 0 : _a.call(
          this,
          id
        );
        this.snippetCommandIds.delete(id);
      }
    }
  }
};
